version: '3'
services:
  backend:
    container_name: my_django_admin
    build:
      context: .
    volumes:
      - static:/app/static
    environment:
      WAIT_HOSTS: ${DB_HOST}:${DB_PORT}
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    image: postgres:14.0-alpine
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}

    volumes:
      - admin_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  nginx:
    container_name: my_nginx
    image: nginx:1.21.6
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/data/static
    ports:
      - 8000:8000
    depends_on:
      - backend
  es:
    container_name: elastic_search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    ports:
      - ${ES_PORT}:${ES_PORT}
    environment:
      - "ES_JAVA_OPTS=-Xms1023m -Xmx1024m"
      - xpack.security.enabled=false
      - discovery.type=single-node

volumes:
  static:
  admin_db:
