version: '3.9'
services:
  admin:
    container_name: admin
    build:
      context: .
    volumes:
      - admin_static:/app/static
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      WAIT_HOSTS: ${DB_HOST}:${DB_PORT}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    depends_on:
      - admin_db
      - nginx
    networks:
      - admin

volumes:
  admin_static:
    external:
      name: movies_admin_static

networks:
  admin:
    name: movies_admin_network
