version: '3.9'

x-airflow-common:
  restart: "no"
  volumes:
    - ./src/etl:/srv/app/src/etl
    - ./src/airflow:/srv/app/src/airflow
    - ./tests:/srv/app/tests

services:
  admin_panel:
    volumes:
      - ./src/admin_panel:/app/src/admin_panel
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}

  admin_db:
    restart: "no"

  redis:
    restart: "no"

  nginx:
    restart: "no"

  movies_api:
    environment:
      UVICORN_RELOAD: 1
      DEBUG: 1
    ports:
      - ${MOVIES_API_PORT}:${MOVIES_API_PORT}
    volumes:
      - ./src/movies_api/:/app/
    command: python main.py
