version: '3.9'

services:
  admin_db:
    restart: "no"
    ports:
      - ${DB_PORT}:${DB_PORT}
  admin_panel:
    volumes:
      - ./src/admin_panel:/app/src/admin_panel
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}

  airflow-worker:
    volumes:
      - ./src/etl:/srv/app/src/etl
      - ./src/airflow:/srv/app/src/airflow
      - ./tests:/srv/app/tests

  redis:
    restart: "no"

  nginx:
    restart: "no"

  movies_api:
    environment:
      UVICORN_RELOAD: 1
      DEBUG: 1
      MOVIES_API_PORT: ${MOVIES_API_PORT}
    volumes:
      - ./src/movies_api:/app/src
      - ./tests/api:/app/tests/api
    command: python main.py
