version: '3.9'

x-admin-db-common:
  volumes:
    - ./src/etl/:/srv/app/src/etl/
    - ./src/airflow/:/srv/app/src/airflow/
    - ./tests/:/srv/app/tests/

services:
  admin_panel:
    volumes:
      - ./src/admin_panel:/app/src/admin_panel
