version: '3'
services:
  backend:
    container_name: my_django_admin
    build:
      context: .
    volumes:
      - static:/app/02_movies_admin/static
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - admin_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  nginx:
    container_name: my_nginx
    image: nginx:1.21.6
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static:/data/static
    ports:
      - 8000:8000
    depends_on:
      - backend
  es:
    container_name: elastic_search
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    ports:
      - ${ES_PORT}:${ES_PORT}
    environment:
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  static:
  admin_db:
